name: Build Docker Images & Push to Registry

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      working-directory: .
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag covid-mx
        docker tag frontend docker.pkg.github.com/jaimehisao/covid-mx
        docker push docker.pkg.github.com/googleinterns/jaimehisao/covid-mx
